# Generated by Django 4.0.3 on 2022-03-22 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('reservation_date', models.DateField(default=datetime.date.today)),
                ('reservation_time', models.TimeField(default=datetime.time)),
                ('service', models.CharField(choices=[('Service 1', 'Service 1'), ('Service 2', 'Service 2'), ('Service 3', 'Service 3')], max_length=200)),
            ],
        ),
    ]
